# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        ClienteBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_db_provider:
            entity:
                class: UserBundle:User
                property: username

    access_control:
        - {path: ^/usuarios/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: my_db_provider
            anonymous: ~
            form_login:
                login_path: /usuarios/login
                check_path: /usuarios/login
            logout:
                path: /usuarios/logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
