<?php

namespace PrincipalBundle\Repository;

/**
 * ActividadTuristaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadTuristaRepository extends \Doctrine\ORM\EntityRepository
{
}
