<?php

namespace PrincipalBundle\Repository;

/**
 * ActividadVoluntarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadVoluntarioRepository extends \Doctrine\ORM\EntityRepository
{
}
