<?php

namespace PrincipalBundle\Repository;

/**
 * contactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contactoRepository extends \Doctrine\ORM\EntityRepository
{
}
